cd /home/u221820373/domains/academiadanzaulises.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/acaibrasa.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/albanileriamamani.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/anasimonhinojo.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/antiquewhite-hornet-257573.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/aquamarine-crocodile-226990.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/aquamarine-herring-599607.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/arquitectosuarez.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/atelierlaregia.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/automovilescataluna.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/babutatransformacion.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/barbosacarpinteria.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/bardepatri.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/barycafe.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/blue-gnu-256534.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/blueviolet-boar-536536.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/blueviolet-cattle-696108.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/blueviolet-porcupine-602966.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/brown-albatross-907711.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/brown-cormorant-576981.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/bustinzataurino.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/cafeteriapalada.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/carpinteriametalicavargas.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/cerealesxmayor.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/cerrajeriaplazadiaz.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/childhoodd.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/comercioalicia.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/construccionesras.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/construccioneszambrano.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/cornflowerblue-llama-899821.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/cortescortesbar.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/cunadeluca.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/cursoscarrillo.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/darkcyan-wombat-682426.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/darkgreen-crane-330167.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/darkslateblue-magpie-995382.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/darkslategrey-porpoise-533397.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/darkslategrey-tapir-262905.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/darkviolet-otter-838616.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/decolurdes.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/distribuidoramateo.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/ecuaboat.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/edgarux.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/ehashimuraterapeuta.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/elparri.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/elpuntopicante.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/esteticagomez.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/europinterck.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/exportyourrwine.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/fontaneria24echarradi.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/fotosballester.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/ganaderiaguardia.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/ginesgonzalaez.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/glovojuarez.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/goldenrod-turkey-937105.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/goldenrod-worm-252478.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/gotow.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/graniteconstruccion.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/gray-mole-161926.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/griselamartinezeventos.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/honeydew-lark-735508.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/indigo-seahorse-825413.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/ivory-dunlin-981973.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/jak-art.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/joanmiquen.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/josemarquezdentalcare.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/josereformas.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/lamodeespinoza.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/lasmanitas.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/lawngreen-okapi-400204.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/letogamultiservicios.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/lightblue-tarsier-747424.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/lightslategrey-otter-910161.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/lightsteelblue-sparrow-596911.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/lightyellow-goshawk-461932.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/logisticayrepartosreyessa.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/lucialeonseguros.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/luischapaypintura.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/maclimatizacion.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/manucerrajeria.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/manuelgarofano.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/marcelinoagricultura.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/marketingweb.com.ar/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/masajesbiomimo.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mayapeluqueria.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mediumblue-chimpanzee-277637.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mediumblue-goat-134304.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mediumspringgreen-duck-871328.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mediumspringgreen-nightingale-573529.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mediumturquoise-cod-639442.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mediumturquoise-hedgehog-707972.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mensajeriaresponsableautonomos.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/michaelandresconstrucciones.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/midnightblue-elk-879100.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mmarinnunez.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/modasescandal.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/mymtalleres.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/olivedrab-dogfish-195685.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/olivedrab-mantis-932044.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/orchid-owl-393074.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/palevioletred-goldfish-153340.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/palevioletred-ram-572286.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/paqueteriasanchez.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/pattyyfranco.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/peachpuff-wildcat-656820.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/peluqueriaelii.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/peru-turtle-866474.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/pescadosymariscos.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/pieropartigianoni.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/pinturasydecoracionesryk.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/procuradoraperez.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/quesadataxi5.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/recaderiakonate.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/recaderiaymensajeriaraaja.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/red-monkey-445795.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/reformasbota.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/reformasffd.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/reformasmontenegro.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/reformasvieira.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/repartosrivera.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/rosamariarodriguezestetica.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/rosybrown-jaguar-479574.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/royalblue-mule-814483.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/saduka.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/salmon-chough-872238.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/silver-turtle-555072.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/skyblue-parrot-331126.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/sofasmanolita.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/sofyglass.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/soladosyalcatadoshr.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/steelblue-goshawk-766432.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/steelblue-hare-144321.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/steelblue-lemur-637230.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/steelblue-worm-236221.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/tiendaricasanchez.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/transportedavid.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/transportemoreno.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/transportesjoseaperez.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/valorastuvivienda.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/vargasreformas.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/violet-woodpecker-899570.hostingersite.com/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/wipergrup.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/xavithazai.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/xn--edinsanchezhostelera-74b.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk ; \
cd /home/u221820373/domains/zapatosymodamiguel.es/public_html && [ -f .htaccess ] && mv .htaccess .hta.bk
